/**
 * @file agent.ts
 * Lightweight stateful agent factory for the AgentOS high-level API.
 *
 * Wraps {@link generateText} and {@link streamText} with per-session conversation
 * history, optional HEXACO-inspired personality shaping, and a named-agent system
 * prompt builder.  Guardrail identifiers are accepted and stored in config but
 * are not actively enforced in this lightweight layer — use the full AgentOS
 * runtime (`AgentOSOrchestrator`) or `agency()` for guardrail enforcement.
 */
import {
  generateText,
  type FallbackProviderEntry,
  type GenerateTextOptions,
  type GenerateTextResult,
  type GenerationHookContext,
  type GenerationHookResult,
  type Message,
  type ToolCallHookInfo,
} from './generateText.js';
import { streamText, type StreamTextResult } from './streamText.js';
import type { IModelRouter } from '../core/llm/routing/IModelRouter.js';
import type { SkillEntry } from '../skills/types.js';
import type {
  AgentOSUsageAggregate,
  AgentOSUsageLedgerOptions,
} from './runtime/usageLedger.js';
import type { BaseAgentConfig } from './types.js';
import { exportAgentConfig, exportAgentConfigJSON, type AgentExportConfig } from './agentExportCore.js';

/**
 * Configuration options for the {@link agent} factory function.
 *
 * Extends `BaseAgentConfig` with backward-compatible convenience fields.
 * All `BaseAgentConfig` fields (rag, discovery, permissions, emergent, voice,
 * etc.) are accepted and stored in config but are not actively wired in the
 * lightweight agent — they will be consumed by `agency()` and the full runtime.
 */
export interface AgentOptions extends BaseAgentConfig {
  /**
   * Top-level usage ledger shorthand for backward compatibility.
   * When present, forwarded to `observability.usageLedger` internally.
   */
  usageLedger?: AgentOSUsageLedgerOptions;
  /**
   * Chain-of-thought reasoning instruction.
   * - `false` — disable CoT injection.
   * - `true` (default for agents) — inject the default CoT instruction when tools are present.
   * - `string` — inject a custom CoT instruction when tools are present.
   */
  chainOfThought?: boolean | string;
  /**
   * Ordered list of fallback providers to try when the primary provider
   * fails with a retryable error (HTTP 402/429/5xx, network errors).
   *
   * Applied to every `generate()`, `stream()`, and `session.send()` /
   * `session.stream()` call made through this agent.
   *
   * @see {@link GenerateTextOptions.fallbackProviders}
   */
  fallbackProviders?: FallbackProviderEntry[];
  /**
   * Callback invoked when a fallback provider is about to be tried.
   *
   * @param error - The error that triggered the fallback.
   * @param fallbackProvider - The provider identifier being tried next.
   */
  onFallback?: (error: Error, fallbackProvider: string) => void;
  /** Model router for intelligent provider selection per-call. */
  router?: IModelRouter;
  /** Pre-generation hook, called before each LLM step. */
  onBeforeGeneration?: (context: GenerationHookContext) => Promise<GenerationHookContext | void>;
  /** Post-generation hook, called after each LLM step. */
  onAfterGeneration?: (result: GenerationHookResult) => Promise<GenerationHookResult | void>;
  /** Pre-tool-execution hook. */
  onBeforeToolExecution?: (info: ToolCallHookInfo) => Promise<ToolCallHookInfo | null>;
  /**
   * Optional memory provider.  When provided:
   * - `session.send()`/`stream()` calls `memory.getContext()` before each turn
   *   and prepends results to the system prompt.
   * - `session.send()`/`stream()` calls `memory.observe()` after each turn
   *   to encode the exchange into long-term memory.
   */
  memoryProvider?: any;
  /**
   * Optional skill entries to inject into the system prompt.
   * Skill content is appended to the system prompt as markdown sections.
   */
  skills?: SkillEntry[];
}

/**
 * A named conversation session returned by `Agent.session()`.
 * Maintains its own message history independently of other sessions on the same agent.
 */
export interface AgentSession {
  /** Stable session identifier supplied to or auto-generated by `Agent.session()`. */
  readonly id: string;
  /**
   * Sends a user message and returns the complete assistant reply.
   * Appends both turns to the session history when `memory` is enabled.
   *
   * @param text - User message text.
   * @returns The full generation result including text, usage, and tool calls.
   */
  send(text: string): Promise<GenerateTextResult>;
  /**
   * Streams a user message and returns streaming iterables.
   * The assistant reply is appended to session history once the `text` promise resolves.
   *
   * @param text - User message text.
   * @returns A {@link StreamTextResult} with async iterables and awaitable aggregates.
   */
  stream(text: string): StreamTextResult;
  /** Returns a snapshot of the current conversation history for this session. */
  messages(): Message[];
  /** Returns persisted usage totals for this session when the usage ledger is enabled. */
  usage(): Promise<AgentOSUsageAggregate>;
  /** Clears all messages from this session's history. */
  clear(): void;
}

/**
 * A stateful agent instance returned by {@link agent}.
 */
export interface Agent {
  /**
   * Generates a single reply without maintaining session history.
   *
   * @param prompt - User prompt text.
   * @param opts - Optional overrides merged on top of the agent's base options.
   * @returns The complete generation result.
   */
  generate(prompt: string, opts?: Partial<GenerateTextOptions>): Promise<GenerateTextResult>;
  /**
   * Streams a single reply without maintaining session history.
   *
   * @param prompt - User prompt text.
   * @param opts - Optional overrides merged on top of the agent's base options.
   * @returns A {@link StreamTextResult}.
   */
  stream(prompt: string, opts?: Partial<GenerateTextOptions>): StreamTextResult;
  /**
   * Returns (or creates) a named {@link AgentSession} with its own conversation history.
   *
   * @param id - Optional session ID. A unique ID is generated when omitted.
   * @returns The session object for this ID.
   */
  session(id?: string): AgentSession;
  /** Returns persisted usage totals for the whole agent or a single session. */
  usage(sessionId?: string): Promise<AgentOSUsageAggregate>;
  /** Releases all in-memory session state held by this agent. */
  close(): Promise<void>;
  /**
   * Exports the agent's configuration as a portable object.
   * @param metadata - Optional human-readable metadata to attach.
   * @returns A portable {@link AgentExportConfig} object.
   */
  export(metadata?: AgentExportConfig['metadata']): AgentExportConfig;
  /**
   * Exports the agent's configuration as a pretty-printed JSON string.
   * @param metadata - Optional human-readable metadata to attach.
   * @returns JSON string.
   */
  exportJSON(metadata?: AgentExportConfig['metadata']): string;
  /** Read current avatar binding state (auto-populated from mood/voice/relationship). */
  getAvatarBindings(): import('./types').AvatarBindingInputs & Record<string, unknown>;
  /** Inject game-specific binding overrides (healthBand, combatMode, etc.). */
  setAvatarBindingOverrides(overrides: Record<string, unknown>): void;
}

function mergeUsageLedgerOptions(
  ...parts: Array<AgentOSUsageLedgerOptions | undefined>
): AgentOSUsageLedgerOptions | undefined {
  const merged = Object.assign({}, ...parts.filter(Boolean));
  return Object.keys(merged).length > 0 ? merged : undefined;
}

async function loadRecordedAgentOSUsage(
  options?: Pick<AgentOSUsageLedgerOptions, 'enabled' | 'path' | 'sessionId' | 'personaId'>
): Promise<AgentOSUsageAggregate> {
  const { getRecordedAgentOSUsage } = await import('./runtime/usageLedger.js');
  return getRecordedAgentOSUsage(options);
}

/** Timeout for memory operations to prevent blocking generation. */
const MEMORY_TIMEOUT_MS = 5000;

function buildSystemPrompt(opts: AgentOptions): string | undefined {
  const sections: string[] = [];

  if (opts.instructions?.trim()) {
    sections.push(opts.instructions.trim());
  }

  if (opts.name?.trim()) {
    sections.push(`Assistant name: ${opts.name.trim()}.`);
  }

  if (opts.personality) {
    const traits = Object.entries(opts.personality)
      .filter(([, value]) => typeof value === 'number' && Number.isFinite(value))
      .map(([key, value]) => `${key}=${Number(value).toFixed(2)}`);
    if (traits.length > 0) {
      sections.push(`Behavior traits: ${traits.join(', ')}.`);
    }
  }

  // Append skill content as markdown sections
  if (opts.skills?.length) {
    for (const entry of opts.skills) {
      if (entry.skill.content?.trim()) {
        sections.push(entry.skill.content.trim());
      }
    }
  }

  return sections.length > 0 ? sections.join('\n\n') : undefined;
}

/**
 * Creates a lightweight stateful agent backed by in-memory session storage.
 *
 * The agent wraps {@link generateText} and {@link streamText} with a persistent
 * system prompt built from `instructions`, `name`, and `personality` fields.
 * Multiple independent sessions can be opened via `Agent.session()`.
 *
 * @param opts - Agent configuration including model, instructions, and optional tools.
 *   All `BaseAgentConfig` fields are accepted; advanced fields (rag, discovery,
 *   permissions, emergent, voice, guardrails, etc.) are stored but not actively
 *   wired in the lightweight layer — they are consumed by `agency()` and the full runtime.
 * @returns An {@link Agent} instance with `generate`, `stream`, `session`, and `close` methods.
 *
 * @example
 * ```ts
 * const myAgent = agent({ model: 'openai:gpt-4o', instructions: 'You are a helpful assistant.' });
 * const session = myAgent.session('user-123');
 * const reply = await session.send('Hello!');
 * console.log(reply.text);
 * ```
 */
export function agent(opts: AgentOptions): Agent {
  const sessions = new Map<string, Message[]>();
  let avatarBindingOverrides: Record<string, unknown> = {};
  const useMemory = opts.memory !== false;

  /*
   * Cognitive mechanisms validation.  When the caller provides a
   * `cognitiveMechanisms` config but has memory disabled, the mechanisms
   * cannot be wired (they depend on CognitiveMemoryManager which needs an
   * active memory subsystem).  Log a warning and drop the config.
   */
  if (opts.cognitiveMechanisms && !useMemory) {
    console.warn(
      '[AgentOS] cognitiveMechanisms config was provided but memory is disabled. ' +
      'Mechanisms require memory to be enabled (set `memory: true` or pass a MemoryConfig). ' +
      'The cognitiveMechanisms config will be ignored.',
    );
  }

  /*
   * Resolve the effective usage ledger config.  The top-level `usageLedger`
   * field is a backward-compat alias — if it is present we forward it to
   * `observability.usageLedger`.  An explicit `observability.usageLedger`
   * takes precedence when both are supplied.
   */
  const effectiveLedger: AgentOSUsageLedgerOptions | undefined =
    (opts.observability?.usageLedger as AgentOSUsageLedgerOptions | undefined) ?? opts.usageLedger;

  const baseOpts: Partial<GenerateTextOptions> = {
    provider: opts.provider,
    model: opts.model,
    system: buildSystemPrompt(opts),
    tools: opts.tools,
    maxSteps: opts.maxSteps ?? 5,
    chainOfThought: opts.chainOfThought ?? true,
    apiKey: opts.apiKey,
    baseUrl: opts.baseUrl,
    usageLedger: effectiveLedger,
    fallbackProviders: opts.fallbackProviders,
    onFallback: opts.onFallback,
    router: opts.router,
    onBeforeGeneration: opts.onBeforeGeneration,
    onAfterGeneration: opts.onAfterGeneration,
    onBeforeToolExecution: opts.onBeforeToolExecution,
  };

  const agentInstance: Agent = {
    async generate(
      prompt: string,
      extra?: Partial<GenerateTextOptions>
    ): Promise<GenerateTextResult> {
      return generateText({
        ...baseOpts,
        ...extra,
        prompt,
        usageLedger: mergeUsageLedgerOptions(baseOpts.usageLedger, extra?.usageLedger, {
          source: extra?.usageLedger?.source ?? 'agent.generate',
        }),
      } as GenerateTextOptions);
    },

    stream(prompt: string, extra?: Partial<GenerateTextOptions>): StreamTextResult {
      return streamText({
        ...baseOpts,
        ...extra,
        prompt,
        usageLedger: mergeUsageLedgerOptions(baseOpts.usageLedger, extra?.usageLedger, {
          source: extra?.usageLedger?.source ?? 'agent.stream',
        }),
      } as GenerateTextOptions);
    },

    session(id?: string): AgentSession {
      const sessionId = id ?? crypto.randomUUID();
      if (!sessions.has(sessionId)) sessions.set(sessionId, []);
      const history = sessions.get(sessionId)!;

      return {
        id: sessionId,

        async send(text: string): Promise<GenerateTextResult> {
          // Memory recall before generation
          let memorySystemMsg: string | undefined;
          if (opts.memoryProvider?.getContext) {
            try {
              const ctx = await Promise.race([
                opts.memoryProvider.getContext(text, { tokenBudget: 2000 }),
                new Promise<null>((resolve) => setTimeout(() => resolve(null), MEMORY_TIMEOUT_MS)),
              ]);
              if (ctx?.contextText) {
                memorySystemMsg = ctx.contextText;
              }
            } catch {
              // Memory recall failure is non-fatal
            }
          }

          // Prepend memory context to system prompt
          let system = baseOpts.system;
          if (memorySystemMsg) {
            system = [memorySystemMsg, system].filter(Boolean).join('\n\n') || undefined;
          }

          const requestMessages = useMemory
            ? [...history, { role: 'user' as const, content: text }]
            : [{ role: 'user' as const, content: text }];
          const result = await generateText({
            ...baseOpts,
            system,
            messages: requestMessages,
            usageLedger: mergeUsageLedgerOptions(baseOpts.usageLedger, {
              sessionId,
              source: 'agent.session.send',
            }),
          } as GenerateTextOptions);
          if (useMemory) {
            history.push({ role: 'user', content: text });
            history.push({ role: 'assistant', content: result.text });
          }

          // Memory observe after generation (fire-and-forget)
          if (opts.memoryProvider?.observe) {
            opts.memoryProvider.observe('user', text).catch(() => {});
            if (result.text) {
              opts.memoryProvider.observe('assistant', result.text).catch(() => {});
            }
          }

          return result;
        },

        stream(text: string): StreamTextResult {
          // For streaming, use onBeforeGeneration hook to inject memory context
          const originalBeforeHook = baseOpts.onBeforeGeneration;

          const result = streamText({
            ...baseOpts,
            messages: useMemory
              ? [...history, { role: 'user' as const, content: text }]
              : [{ role: 'user' as const, content: text }],
            onBeforeGeneration: opts.memoryProvider?.getContext
              ? async (ctx) => {
                  // Inject memory context
                  try {
                    const memCtx = await Promise.race([
                      opts.memoryProvider!.getContext(text, { tokenBudget: 2000 }),
                      new Promise<null>((resolve) => setTimeout(() => resolve(null), MEMORY_TIMEOUT_MS)),
                    ]);
                    if (memCtx?.contextText) {
                      ctx = {
                        ...ctx,
                        messages: [
                          { role: 'system' as const, content: memCtx.contextText },
                          ...ctx.messages,
                        ],
                      };
                    }
                  } catch { /* non-fatal */ }
                  // Chain with user's hook if present
                  if (originalBeforeHook) {
                    const userResult = await originalBeforeHook(ctx);
                    return userResult ?? ctx;
                  }
                  return ctx;
                }
              : originalBeforeHook,
            usageLedger: mergeUsageLedgerOptions(baseOpts.usageLedger, {
              sessionId,
              source: 'agent.session.stream',
            }),
          } as GenerateTextOptions);
          // Capture text for history when done
          if (useMemory) {
            history.push({ role: 'user', content: text });
            void result.text
              .then((replyText) => {
                history.push({ role: 'assistant', content: replyText });
                // Memory observe after stream completes
                if (opts.memoryProvider?.observe) {
                  opts.memoryProvider.observe('user', text).catch(() => {});
                  opts.memoryProvider.observe('assistant', replyText).catch(() => {});
                }
              })
              .catch(() => {
                /* history update failed, non-critical */
              });
          }
          return result;
        },

        messages(): Message[] {
          return [...history];
        },

        async usage(): Promise<AgentOSUsageAggregate> {
          return loadRecordedAgentOSUsage({
            enabled: baseOpts.usageLedger?.enabled,
            path: baseOpts.usageLedger?.path,
            sessionId,
          });
        },

        clear() {
          history.length = 0;
        },
      };
    },

    async usage(sessionId?: string): Promise<AgentOSUsageAggregate> {
      return loadRecordedAgentOSUsage({
        enabled: baseOpts.usageLedger?.enabled,
        path: baseOpts.usageLedger?.path,
        sessionId,
      });
    },

    async close() {
      sessions.clear();
    },

    /**
     * Exports this agent's configuration as a portable object.
     * @param metadata - Optional human-readable metadata to attach.
     * @returns A portable {@link AgentExportConfig} object.
     */
    export(metadata?: AgentExportConfig['metadata']): AgentExportConfig {
      return exportAgentConfig(agentInstance, metadata);
    },

    /**
     * Exports this agent's configuration as a pretty-printed JSON string.
     * @param metadata - Optional human-readable metadata to attach.
     * @returns JSON string with 2-space indentation.
     */
    exportJSON(metadata?: AgentExportConfig['metadata']): string {
      return exportAgentConfigJSON(agentInstance, metadata);
    },

    getAvatarBindings() {
      const cfg = opts.avatar;
      if (!cfg?.enabled) return {} as any;
      const base: Record<string, unknown> = {
        speaking: false,
        emotion: 'neutral',
        intensity: 0,
        stress: 0,
        anger: 0,
        affection: 0,
        trust: 0,
        relationshipWarmth: 0,
      };
      return { ...base, ...avatarBindingOverrides };
    },

    setAvatarBindingOverrides(overrides: Record<string, unknown>) {
      avatarBindingOverrides = { ...avatarBindingOverrides, ...overrides };
    },
  };

  // Stash the original config as a non-enumerable property so that
  // exportAgentConfig() can retrieve it without polluting the public API.
  Object.defineProperty(agentInstance, '__config', {
    value: opts,
    enumerable: false,
    configurable: true,
  });

  return agentInstance;
}
