/**
 * @file agent.ts
 * Lightweight stateful agent factory for the AgentOS high-level API.
 *
 * Wraps {@link generateText} and {@link streamText} with per-session conversation
 * history, optional HEXACO-inspired personality shaping, and a named-agent system
 * prompt builder.  For full guardrail enforcement or production multi-agent
 * orchestration use the AgentOS runtime (`AgentOSOrchestrator`) instead.
 */
import { generateText, type GenerateTextOptions, type GenerateTextResult, type Message } from './generateText.js';
import { streamText, type StreamTextResult } from './streamText.js';
import type { ToolDefinitionMap } from './toolAdapter.js';
import {
  getRecordedAgentOSUsage,
  type AgentOSUsageAggregate,
  type AgentOSUsageLedgerOptions,
} from './usageLedger.js';

/**
 * Configuration options for the {@link agent} factory function.
 */
export interface AgentOptions {
  /**
   * Provider name.  When supplied without `model`, the default text model for
   * the provider is resolved automatically from the built-in defaults registry.
   *
   * @example `"openai"`, `"anthropic"`, `"ollama"`
   */
  provider?: string;
  /**
   * Model used for every call made by this agent.  Accepted in two formats:
   * - `"provider:model"` — legacy format (e.g. `"openai:gpt-4o"`), still fully supported.
   * - Plain model name (e.g. `"gpt-4o-mini"`) when `provider` is also set.
   *
   * Either `provider` or `model` (or an API key env var for auto-detection) is required.
   */
  model?: string;
  /** Display name injected into the system prompt (e.g. `"Aria"`). */
  name?: string;
  /** Free-form system instructions prepended before personality and name lines. */
  instructions?: string;
  /** Named tools available to the agent on every call. */
  tools?: ToolDefinitionMap;
  /**
   * Enable in-memory conversation history for sessions.
   * When `false`, each `send` / `stream` call is stateless.  Defaults to `true`.
   */
  memory?: boolean;
  /**
   * HEXACO-inspired personality trait overrides (0–1 scale).
   * Encoded as a human-readable trait string appended to the system prompt.
   */
  personality?: Partial<{
    honesty: number; emotionality: number; extraversion: number;
    agreeableness: number; conscientiousness: number; openness: number;
  }>;
  /**
   * Guardrail policy identifiers.
   * **Not supported** in the lightweight API — passing any values throws immediately.
   * Use `AgentOSOrchestrator` for real guardrail enforcement.
   */
  guardrails?: string[];
  /** Override the provider API key instead of reading from environment variables. */
  apiKey?: string;
  /** Override the provider base URL (useful for local proxies or Ollama). */
  baseUrl?: string;
  /** Maximum agentic steps per call. Defaults to `5`. */
  maxSteps?: number;
  /** Optional durable usage ledger configuration for helper-level accounting. */
  usageLedger?: AgentOSUsageLedgerOptions;
}

/**
 * A named conversation session returned by {@link Agent.session}.
 * Maintains its own message history independently of other sessions on the same agent.
 */
export interface AgentSession {
  /** Stable session identifier supplied to or auto-generated by {@link Agent.session}. */
  readonly id: string;
  /**
   * Sends a user message and returns the complete assistant reply.
   * Appends both turns to the session history when `memory` is enabled.
   *
   * @param text - User message text.
   * @returns The full generation result including text, usage, and tool calls.
   */
  send(text: string): Promise<GenerateTextResult>;
  /**
   * Streams a user message and returns streaming iterables.
   * The assistant reply is appended to session history once the `text` promise resolves.
   *
   * @param text - User message text.
   * @returns A {@link StreamTextResult} with async iterables and awaitable aggregates.
   */
  stream(text: string): StreamTextResult;
  /** Returns a snapshot of the current conversation history for this session. */
  messages(): Message[];
  /** Returns persisted usage totals for this session when the usage ledger is enabled. */
  usage(): Promise<AgentOSUsageAggregate>;
  /** Clears all messages from this session's history. */
  clear(): void;
}

/**
 * A stateful agent instance returned by {@link agent}.
 */
export interface Agent {
  /**
   * Generates a single reply without maintaining session history.
   *
   * @param prompt - User prompt text.
   * @param opts - Optional overrides merged on top of the agent's base options.
   * @returns The complete generation result.
   */
  generate(prompt: string, opts?: Partial<GenerateTextOptions>): Promise<GenerateTextResult>;
  /**
   * Streams a single reply without maintaining session history.
   *
   * @param prompt - User prompt text.
   * @param opts - Optional overrides merged on top of the agent's base options.
   * @returns A {@link StreamTextResult}.
   */
  stream(prompt: string, opts?: Partial<GenerateTextOptions>): StreamTextResult;
  /**
   * Returns (or creates) a named {@link AgentSession} with its own conversation history.
   *
   * @param id - Optional session ID. A unique ID is generated when omitted.
   * @returns The session object for this ID.
   */
  session(id?: string): AgentSession;
  /** Returns persisted usage totals for the whole agent or a single session. */
  usage(sessionId?: string): Promise<AgentOSUsageAggregate>;
  /** Releases all in-memory session state held by this agent. */
  close(): Promise<void>;
}

function mergeUsageLedgerOptions(
  ...parts: Array<AgentOSUsageLedgerOptions | undefined>
): AgentOSUsageLedgerOptions | undefined {
  const merged = Object.assign({}, ...parts.filter(Boolean));
  return Object.keys(merged).length > 0 ? merged : undefined;
}

function buildSystemPrompt(opts: AgentOptions): string | undefined {
  const sections: string[] = [];

  if (opts.instructions?.trim()) {
    sections.push(opts.instructions.trim());
  }

  if (opts.name?.trim()) {
    sections.push(`Assistant name: ${opts.name.trim()}.`);
  }

  if (opts.personality) {
    const traits = Object.entries(opts.personality)
      .filter(([, value]) => typeof value === 'number' && Number.isFinite(value))
      .map(([key, value]) => `${key}=${Number(value).toFixed(2)}`);
    if (traits.length > 0) {
      sections.push(`Behavior traits: ${traits.join(', ')}.`);
    }
  }

  return sections.length > 0 ? sections.join('\n\n') : undefined;
}

/**
 * Creates a lightweight stateful agent backed by in-memory session storage.
 *
 * The agent wraps {@link generateText} and {@link streamText} with a persistent
 * system prompt built from `instructions`, `name`, and `personality` fields.
 * Multiple independent sessions can be opened via {@link Agent.session}.
 *
 * @param opts - Agent configuration including model, instructions, and optional tools.
 * @returns An {@link Agent} instance with `generate`, `stream`, `session`, and `close` methods.
 * @throws {Error} If `opts.guardrails` contains any entries (not supported in the lightweight API).
 *
 * @example
 * ```ts
 * const myAgent = agent({ model: 'openai:gpt-4o', instructions: 'You are a helpful assistant.' });
 * const session = myAgent.session('user-123');
 * const reply = await session.send('Hello!');
 * console.log(reply.text);
 * ```
 */
export function agent(opts: AgentOptions): Agent {
  if (opts.guardrails && opts.guardrails.length > 0) {
    throw new Error(
      'agent({ guardrails }) is not supported in the lightweight high-level API. Use the full AgentOS runtime for real guardrail enforcement.',
    );
  }

  const sessions = new Map<string, Message[]>();
  const useMemory = opts.memory !== false;

  const baseOpts: Partial<GenerateTextOptions> = {
    provider: opts.provider,
    model: opts.model,
    system: buildSystemPrompt(opts),
    tools: opts.tools,
    maxSteps: opts.maxSteps ?? 5,
    apiKey: opts.apiKey,
    baseUrl: opts.baseUrl,
    usageLedger: opts.usageLedger,
  };

  return {
    async generate(prompt: string, extra?: Partial<GenerateTextOptions>): Promise<GenerateTextResult> {
      return generateText({
        ...baseOpts,
        ...extra,
        prompt,
        usageLedger: mergeUsageLedgerOptions(
          baseOpts.usageLedger,
          extra?.usageLedger,
          { source: extra?.usageLedger?.source ?? 'agent.generate' },
        ),
      } as GenerateTextOptions);
    },

    stream(prompt: string, extra?: Partial<GenerateTextOptions>): StreamTextResult {
      return streamText({
        ...baseOpts,
        ...extra,
        prompt,
        usageLedger: mergeUsageLedgerOptions(
          baseOpts.usageLedger,
          extra?.usageLedger,
          { source: extra?.usageLedger?.source ?? 'agent.stream' },
        ),
      } as GenerateTextOptions);
    },

    session(id?: string): AgentSession {
      const sessionId = id ?? `session-${Date.now()}`;
      if (!sessions.has(sessionId)) sessions.set(sessionId, []);
      const history = sessions.get(sessionId)!;

      return {
        id: sessionId,

        async send(text: string): Promise<GenerateTextResult> {
          const requestMessages = useMemory
            ? [...history, { role: 'user' as const, content: text }]
            : [{ role: 'user' as const, content: text }];
          const result = await generateText({
            ...baseOpts,
            messages: requestMessages,
            usageLedger: mergeUsageLedgerOptions(
              baseOpts.usageLedger,
              { sessionId, source: 'agent.session.send' },
            ),
          } as GenerateTextOptions);
          if (useMemory) {
            history.push({ role: 'user', content: text });
            history.push({ role: 'assistant', content: result.text });
          }
          return result;
        },

        stream(text: string): StreamTextResult {
          const result = streamText({
            ...baseOpts,
            messages: useMemory
              ? [...history, { role: 'user' as const, content: text }]
              : [{ role: 'user' as const, content: text }],
            usageLedger: mergeUsageLedgerOptions(
              baseOpts.usageLedger,
              { sessionId, source: 'agent.session.stream' },
            ),
          } as GenerateTextOptions);
          // Capture text for history when done
          if (useMemory) {
            history.push({ role: 'user', content: text });
            result.text.then((replyText) => history.push({ role: 'assistant', content: replyText }));
          }
          return result;
        },

        messages(): Message[] {
          return [...history];
        },

        async usage(): Promise<AgentOSUsageAggregate> {
          return getRecordedAgentOSUsage({
            enabled: baseOpts.usageLedger?.enabled,
            path: baseOpts.usageLedger?.path,
            sessionId,
          });
        },

        clear() {
          history.length = 0;
        },
      };
    },

    async usage(sessionId?: string): Promise<AgentOSUsageAggregate> {
      return getRecordedAgentOSUsage({
        enabled: baseOpts.usageLedger?.enabled,
        path: baseOpts.usageLedger?.path,
        sessionId,
      });
    },

    async close() {
      sessions.clear();
    },
  };
}
